### ISSUE TITLE
payload / params magic gone

### ISSUE THREAD

**Issue by rdallman** [iron-io/dockerworker#1]
I think this was a design goal and think it's fine, but now tasks can't simply access the payload from, e.g. `@payload` like they were able to before -- this requires some changes to the current user code and we should make a note of it to warn them ahead of time (or consider superior alternatives).

**Comment by treeder** [comment]
Ya, I think we'll want to create new libs or add to existing libs a couple of helper functions. But these libs would be tiny, like this helper for Ruby: https://github.com/iron-io/dockerworker/blob/master/iron_worker.rb

Thoughts?

**Comment by rdallman** [comment]
yea, I think that's great.

**Comment by treeder** [comment]
Actually, most of our other libs should work the same way they do now in terms of loading payloads and what not, I think the Ruby one is the only strange one because ng did special magic for Ruby libs.

**Comment by pulkitsinghal** [comment]
Is this why `node hello.js --payload hello.payload.json` from the https://github.com/iron-io/dockerworker/tree/master/node `README` doesn't work? It prints null for all values. If so when will this get fixed?
