### ISSUE TITLE
How to use dockerworker in a turnkey fashion?

### ISSUE THREAD

**Issue by pulkitsinghal** [iron-io/dockerworker#11]
First of all, I highly recommend looking into opening a gitter.im chat room for any and all repos (start with this one) that are hosted on https://github.com/iron-io ... it will make for a smoother conversation.

I was attempting to use the vanilla IronWorker to setup a turnkey deployment but that failed because node_modules aren't remotely downloaded and built properly for some reason unknown to me in iron infrastructure (let me know where to file a bug in GitHub for that) ... so @treeder's recommendation I tried out dockerworker and although it looks like fun, it doesn't really have that deployment ease of one command: `iron_worker upload https://raw.github.com/shoppinpal/warehouse-manager-generate-stock-order/master/warehouse.manager.generate.stock.order.worker`

... so what's my alternative here in the dockerworker scenario?

**Comment by pulkitsinghal** [comment]
I hope it makes sense where I'm coming from, its one thing for users to leverage code from GitHub by pointing to its worker file and having it be built and deployed on their own Iron account. And its completely different to clone repo locally, run npm install, then zip it and then deploy it to one's own Iron account.

**Comment by treeder** [comment]
Ya, dockerworker wasn't really built for the turnkey stuff. Let us think about this one and get back to you, might be another way such as storing the final zip code package somewhere and allowing others to get it.

**Comment by treeder** [comment]
I think we found a decent solution for this using the Docker workflow allowing you to upload worker zips via URL. Will let you know when it's ready.

**Comment by treeder** [comment]
@pulkitsinghal the solution we're thinking about is to be able to upload a worker zip from anywhere, so no remote build time or anything. eg:

```
iron worker upload http://...../myworker.zip 
```

**Comment by treeder** [comment]
The new solution is to make a docker image for your worker.
