### ISSUE TITLE
require_relative prevents Ruby example from running

### ISSUE THREAD

**Issue by theIV** [iron-io/dockerworker#13]
Hi there,

The Ruby example README starts off by telling us to `bundle install` and then to run the example. This blows up unless we actually did `bundle install --standalone`, but we're only told to do this further down in the example and "inside" the Docker container.

The error is as follows:

``` sh
hello.rb:1:in `require_relative': cannot load such file -- [...]/dockerworker/ruby/bundle/bundler/setup (LoadError)
        from hello.rb:1:in `<main>''
```

I'm not sure if that means the best course is to tell them to `bundle install --standalone` right out of the gate, or remove the `require_relative` line from `hello.rb`.

I can make a PR if there's a course you would prefer going in.

Thanks for the examples!

**Comment by treeder** [comment]
The point of the stuff at the start was to show that it doesn't work unless you do `--standalone`, but I think I may just remove that stuff. Seems to be confusing people, I've already got this change ready so just pushed it.

**Comment by treeder** [comment]
Better?

**Comment by theIV** [comment]
I think that's much better. Thanks, @treeder!
