### ISSUE TITLE
execute docker npm install not working for node example (windows)

### ISSUE THREAD

**Issue by xo-chris** [iron-io/dockerworker#29]
Hi there

I am trying to follow this tutorial, in node.js.  I have the pre-requisites installed and have cloned this git project into a directory that I bash into.  I execute:

$ docker run --rm -v "//$PWD":/worker -w //worker iron/node:dev npm install

and get back the below stack trace

(Note:  the double forward slashes are deliberate, I am using a windows machine and so am using this as per email correspondence with Alex Litvak.  They do work, in the sense that if I use: echo "//$PWD" I get back the current directory that I am in)

npm ERR! install Couldn't read dependencies
npm ERR! Linux 4.1.12-boot2docker
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! path /worker/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open '/worker/package.j
son'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directo
ry.

npm ERR! Please include the following file with any support request:
npm ERR!     /worker/npm-debug.log

**Comment by alex-litvak** [comment]
@kiwichris1 Seems like you're running the "docker run ..." command from wrong directory, share the contents please

**Comment by xo-chris** [comment]
Hi Alex

I am in the right directory I think?

 Here is a screenshot that shows my directory structure and what I am doing
and the response
![image](https://cloud.githubusercontent.com/assets/15866321/11334067/67a82df8-9237-11e5-9731-8a66efc34a68.png)

Thanks

Chris

On Mon, Nov 23, 2015 at 10:52 PM, alex-litvak notifications@github.com
wrote:

> @kiwichris1 https://github.com/kiwichris1 Seems like you're running the
> "docker run ..." command from wrong directory, share the contents please
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/iron-io/dockerworker/issues/29#issuecomment-158890872
> .

## 

Chris Lennon
Exosphere

**Comment by alex-litvak** [comment]
Solved: the worker should be placed in the home directory (C:\Users\USER_NAME....) to be shared with docker host
