### ISSUE TITLE
Error when curling the webhook url

### ISSUE THREAD

**Issue by ghost** [iron-io/dockerworker#38]
Hi,

I get the following error when I curl the webhook endpoint for my worker:

`{"msg":"Token required for authentication"}`

Here is the curl command:

```
curl -XPOST https://worker-aws-us-east-1.iron.io/2/projects/{$My_Project}/tasks/webhook?code_name=HelloWorkerPython&oauth={$My_Token}
```

Anything else I need to do?

thanks!

**Comment by rdallman** [comment]
curl utility forces escaping of query parameters. recommend either using `Authorization: OAuth $token` header or `\?oauth\=$token`. closing this since it's not relevant to dockerworker, but feel free to follow up here.

**Comment by ghost** [comment]
thanks for the help. worked!
