### ISSUE TITLE
C++ compilation task that leverages make

### ISSUE THREAD

**Issue by Ravenwater** [iron-io/dockerworker#40]
The gcc microcontainer is not a realistic use case for compiling and building C/C++ code. The richness of the compilation universe is managed by task runners that can build their own dependencies, like make, ant, grunt, gulp, bazel, etc.

Any effort to create a container that is more realistic for building C/C++?

All these build tools have parallelization already built in, so there is going to be a fight between who is doing what.

**Comment by treeder** [comment]
We don't use c/c++ much so it's not something we're going to put a lot of effort into. We're happy to take contributions though.
