### ISSUE TITLE
Task status: error

### ISSUE THREAD

**Issue by fattenap** [iron-io/dockerworker#5]
Hi,

I followed the go tutorial and created the worker. When run in the Docker environment it builds and runs ok. I zip the files and upload the file with 
`iron worker upload --stack go-1.4 hello-go.zip ./hello` and get the following output

`----->  Configuring client
        Project 'playground' with id='54dc026b1733cc0006000126'
----->  Uploading worker ""
        Code package uploaded code with id="54e571bd61d618646c031cc7"
        Check 'https://hud.iron.io/tq/projects/54dc026b1733cc0006000126/code/54e571bd61d618646c031cc7' for more info`
But my task status is `error` with the following message
msg `undefined method `split' for #<CodeHistory:0x000000056001a8>`

Is this what's suppose to happen?

Thanks

**Comment by treeder** [comment]
No, that's not what's supposed to happen. This stuff isn't ready to go yet, still in dev/testing. :)

How'd you come across it?

**Comment by fattenap** [comment]
No problem.

The error is displayed on my iron.io dashboard worker list. The hello-go worker shows errors in the Task List. Then when I click through it shows a status of error. I've attached some screen shots. I hope that's ok.

![image](https://cloud.githubusercontent.com/assets/4471171/6277879/71e690d2-b8e6-11e4-98e0-eaf9afc3dd92.png)
![image](https://cloud.githubusercontent.com/assets/4471171/6277890/84933e38-b8e6-11e4-9026-1b337ed65411.png)
![image](https://cloud.githubusercontent.com/assets/4471171/6277906/a20a6838-b8e6-11e4-834e-073100ee9b95.png)

Sorry I'm new to docker/iron.io and still trying to understand how everything fits.

**Comment by treeder** [comment]
@fattenap although this is an unreleased feature as of now, the go example should work.
