### ISSUE TITLE
Readme warning about large installation, maybe I'm doing it wrong?

### ISSUE THREAD

**Issue by jhendley25** [iron-io/dockerworker#8]
First off, good stuff! I'm stoked to migrate from .worker to the new docker setup.

Working through the ruby example, I ran:

``` sh
docker run --rm -v "$(pwd)":/worker -w /worker iron/images:ruby-2.1 sh -c 'ruby hello.rb -payload hello.payload.json -config hello.config.yml -id 123'
```

...which resulted in quite a few downloads totaling 400mb+. Looks like the readme says something to the effect of "doh, that didn't work", but I did not reach that point since I have a relatively slow connection at home (< 2mbs) and possibly canceled before getting there:
![screen shot 2015-03-30 at 11 55 55 pm](https://cloud.githubusercontent.com/assets/5239363/6912081/68e595e4-d738-11e4-963c-a9b71b9e5bfe.png)

If that is not the case, it would probably be good to warn people about the size of the download.

**Comment by treeder** [comment]
Hi @jhendley25 , as with any Docker image, the first pull is slow since it's pulling a complete operating system down. Every time after should be fast though. Adding a note to the docs about it is probably a good idea though.

**Comment by jhendley25** [comment]
Ok cool, I'll definitely try again on a faster connection. Thanks for the heads up.
